-- 000001_init_schema.down.sql
-- Откат схемы Academy Genius

DROP TABLE IF EXISTS problems_solved CASCADE;
DROP TABLE IF EXISTS knowledge_map CASCADE;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS alumni_awards CASCADE;
DROP TABLE IF EXISTS alumni CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS problems CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS users CASCADE;